# 协程

## 1. 协程的挂起

​	协程的挂起指当协程运行到一个挂起函数，如suspend函数，Delay()，await()函数等，当协程运行到这个函数时，协程会切走到其他地方执行这些函数（具体运行在哪里取决于挂起函数的Dispatcher决定），并提前结束当前协程的调用，避免阻塞当前的线程，当挂起函数执行完毕后，协程就会恢复调用，继续后面的代码执行（await() 存疑）



## 2. 协程调度器Dispatcher

​	由启动协程时指定的Dispatcher指定，大致有以下四种

 	1. Dispatchers.IO 线程池
 	2. Dispatchers.Main 主线程 不同平台有不同实现
 	3. Dispatchers.Default 线程池
 	4. Dispatchers.Unconfined 在运行到一个挂起点之前都是运行在调用它的线程里，当执行到挂起函数并在恢复后，运行在哪里取决于挂起函数执行在哪里，也就是说使用这个调度器，当切换到其他线程之后就不会恢复过来了，挂起函数切换到哪里，就继续在哪里执行

## 3. 协程的异常

### 概念

​	协程的异常传播方式有两种，第一种是向上抛出（launch，actor），一种是不抛出，交给用户消耗（如async , 只有当用户调用await时才会抛出相关异常）。当这些协程构建器创建一个根协程(不是其他协程的子协程)时，抛出的异常会被视为未被捕捉的异常，类似于Java线程的uncaughtExceptionHandler，在android中抛出时则会调用uncaughtExceptionPreHandler 来处理这些未处理的异常，如果不妥善处理会造成app崩溃。而后一种则会交给用户自行处理，不会主动抛出（处理方法，比如在用async时就用try catch包裹await方法）

### CoroutineException

​	可以通过自定义一个CoroutineExceptionHandler作为上下文用来处理根协程中为捕获的异常，不过无法从CoroutineExceptionHandler中恢复，让程序继续往异常产生处后执行，因为当handler被调用时，协程已经执行完毕并抛出了相关异常，CoroutineExceptionHandler通常是用来记录异常，重启或者关闭应用的。这种方式一般只是针对设置了CoroutineExceptionHandler的根协程有效（Global.launch等），未设置的还是交给平台默认的处理方式处理

​	但如果是在JVM上，我们可以重定义一个全局的异常处理器来将所有的协程通过ServiceLoader注册到CoroutineExceptionHandler，全局异常处理者就像Thread.defaultUncatchExceptionHandler一样，在没有其他异常处理者来处理某个异常时就交由全部异常处理者来处理，在Android中，uncaughtExceptionPreHandler 被设置在全局协程异常处理者中。

​	注意，CoroutineExceptionHandler只会在没有任何其他方式处理的异常被抛出时才会被调用（用try-catch包裹根协程是没用的...，要在异常产生的地方处理里异常才算异常被处理了，出了协程范围外，就算是没有处理者来处理协程内的这个异常了，所以会调用handler来处理），另外，子协程的异常会委托给父协程，层层往上抛，所以给子协程设置的CoroutineExceptionHandler不会被调用，还用第二类异常处理方式中启动的那些协程也不会调用handler

​	当一个协程被取消时会抛出CancellationException，这个异常会被协程忽略，不过可以被try-catch捕获。

​	当一个协程遇到了CancellationException以外的异常它就会尝试取消父协程，这个行为不能被改变，主要是为了给结构化并发提供稳定的协程层次结构（如一个协程中有两个子协程，一个请求token，一个请求用户信息，后者依赖前者的token，为了保证运行正常，所以在第一个子协程失败时就应该取消整个父协程），子协程也不能使用CoroutineExceptionHandler

​	[CoroutineExceptionHandler](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-exception-handler/index.html) 总是被设置在由 [GlobalScope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/index.html) 启动的协程中。将异常处理者设置在 [runBlocking](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html) 主作用域内启动的协程中是没有意义的，尽管子协程已经设置了异常处理者， 但是主协程也总是会被取消的。

​	当有多个异常时，第一个被抛出的异常会被handler处理，其他的异常会被放到throwable的suppress中（这个只有在JDK7以上且支持suppress的环境中才有cancellation会被忽略掉）

### 监督协程

#### 监督作业 SupervisorJob

​	类似于常规Job，创建协程时将SupervisorJob的实例传入即可，与常规job的不同之处在于用这个job启动的协程遇到了错误取消只会向下传播（即只会取消它[指使用了那个job的协程]下面的子协程及自身，不会影响到父协程中的其他代码运行）

```kotlin
/**
 * 使用了[SupervisorJob]的协程，在内部出现异常时，只会影响到
 * 自身及子协程，而兄弟协程和父协程不会被取消
 */
suspend fun supervisorJobExceptionDeal() {
    GlobalScope.launch {
        val supervisorJob = SupervisorJob()
        launch(supervisorJob + CoroutineExceptionHandler { coroutineContext, throwable ->  println(throwable.message)}) {
            println("1")
            launch {
                delay(500)
                println("2")
                //抛出这个异常时，使用job的这个协程会被整个取消掉
                //因此3不会被打印出来
                throw Exception("fffff")
            }
            launch {
                delay(1000)
                println("3")
            }
        }
        launch {
            delay(2000)
            println("4")
        }
        println("5")
    }.join()
}

```

#### 监督作业 SupervisorJob

类似于普通CoroutineScope，和SupervisorJob类似，也是取消只会单向传播，在自身内部出现异常之后就会取消内部子协程及自身的运行

```kotlin
/**
 * 使用了[supervisorScope]的协程，可以代替CoroutineScope，在其内部启动
 * 的协程,同[SupervisorJob]类似，在内部发生异常时，不管是自身的异常还是子协
 * 程的异常，都只会影响到自身这一脉，不会影响[supervisorScope]内直接启动的协程运行
 * （会一直取消到supervisorScope内启动的那个launch启动的协程，其实感觉并不是完全单向
 * 传递的）
 */
suspend fun supervisorScopeExceptionDeal() {
    supervisorScope {
        println("1")
        launch(CoroutineExceptionHandler { coroutineContext, throwable ->  println(throwable.message)}) {
            launch {
                launch {
                    delay(500)
                    println("2")
                    //这个异常抛出后，这个使用了handler的协程会被整个取消掉
                    //因此3、4不会被打印
                    throw Exception("EEEEEEEE")
                }
                delay(600)
                println("3")
            }
            launch {
                delay(1000)
                println("4")
            }

        }
        launch {
            delay(2000)
            println("5")
        }
        println("6")
    }

}
```

#### 普通协程和监督协程的区别

监督协程和普通协程的区别在于由于监督协程中的异常不会向父协程传播，所以
监督协程中的异常都应该自己通过异常处理机制去处理自己的异常，此外，使用了
[SupervisorJob]的协程和[supervisorScope]内直接启动的协程都可以使用
[CoroutineExceptionHandler]（一般情况下CoroutineExceptionHandler
只作用于根协程上，[GlobalScope.launch]函数上）

​	



